# Handling Missing Values

## Learning objectives
- Inspect missing data.
- Impute numeric and categorical features.
- Understand why preprocessing should be fitted on training data only.

This notebook uses a small built-in example and needs no downloads.

In [1]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    "Age": [22, 35, np.nan, 45, 28, np.nan, 50],
    "Fare": [7.25, 12.00, 8.05, np.nan, 21.50, 9.00, 30.00],
    "Embarked": ["S", "C", "S", "Q", np.nan, "S", "C"],
    "Survived": [0, 1, 0, 1, 1, 0, 1],
})
df

    Age   Fare Embarked  Survived
0  22.0   7.25        S         0
1  35.0  12.00        C         1
2   NaN   8.05        S         0
3  45.0    NaN        Q         1
4  28.0  21.50      NaN         1
5   NaN   9.00        S         0
6  50.0  30.00        C         1

## 1. Inspect missing values
`isna()` identifies missing entries; summing its Boolean results counts them per column.

In [2]:
df.isna().sum()

Age         2
Fare        1
Embarked    1
Survived    0
dtype: int64

In [3]:
df.isna().mean().mul(100).round(2)

Age         28.57
Fare        14.29
Embarked    14.29
Survived     0.00
dtype: float64

## 2. Separate features and target

In [4]:
X = df.drop(columns="Survived")
y = df["Survived"]
print("Feature shape:", X.shape)
print("Target shape:", y.shape)

Feature shape: (7, 3)
Target shape: (7,)

## 3. Impute numeric features
`SimpleImputer(strategy="median")` replaces missing values with each column's median. In a predictive workflow, fit it on training data only.

In [5]:
from sklearn.impute import SimpleImputer

numeric_features = ["Age", "Fare"]
numeric_imputer = SimpleImputer(strategy="median")
X_numeric = pd.DataFrame(
    numeric_imputer.fit_transform(X[numeric_features]),
    columns=numeric_features, index=X.index
)
X_numeric

    Age   Fare
0  22.0   7.25
1  35.0  12.00
2  35.0   8.05
3  45.0  10.50
4  28.0  21.50
5  35.0   9.00
6  50.0  30.00

## 4. Impute categorical features
The most frequent category is one option; a constant label such as `Unknown` can be useful when missingness itself matters.

In [6]:
categorical_features = ["Embarked"]
mode_imputer = SimpleImputer(strategy="most_frequent")
X_categorical = pd.DataFrame(
    mode_imputer.fit_transform(X[categorical_features]),
    columns=categorical_features, index=X.index
)
X_categorical

  Embarked
0        S
1        C
2        S
3        Q
4        S
5        S
6        C

In [7]:
constant_imputer = SimpleImputer(strategy="constant", fill_value="Unknown")
X_unknown = pd.DataFrame(
    constant_imputer.fit_transform(X[categorical_features]),
    columns=categorical_features, index=X.index
)
X_unknown

  Embarked
0        S
1        C
2        S
3        Q
4  Unknown
5        S
6        C

## Key takeaways
- Inspect missingness before choosing a strategy.
- Median imputation is often useful for numeric features.
- Use most-frequent or constant imputation for categorical features when appropriate.
- Fit imputers on training data only to avoid data leakage.